### ISSUE TITLE
Debian image needs "locales" package

### ISSUE THREAD

**Issue by kanru** [toolbx-images/images#30]
Hi,

I'm not sure whether this is a glibc >= 2.35 bug or not.

In the current debian unstable toolbox image, do the following will create a broken container

```bash
$ toolbox create --image quay.io/toolbx-images/debian-toolbox:unstable
$ toolbox enter debian-toolbox-unstable
$ sudo apt update
$ sudo apt upgrade -y
$ bash
Segmentation fault (core dumped)
```

Install the locales package and generate the locale files set in env (e.g. en_US.UTF-8) then bash doesn't crash

```bash
$ sudo apt install locales
$ sudo dpkg-reconfigure locales
```

But if I try to set a nonexistent locale, programs including gdb, bash, crash again.

```
$ LC_ALL=ja_JP.UTF-8 bash
bash: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)
Segmentation fault (core dumped)
$ LC_ALL=ja_JP.UTF-8 gdb bash


Fatal signal: Segmentation fault
----- Backtrace -----
0x55ed3e1e8dcf ???
0x55ed3e2df312 ???
0x55ed3e2df488 ???
0x7f0b4a39ba9f ???
0x7f0b4a4b5b59 ???
0x7f0b4b412204 _rl_init_locale
0x7f0b4b4122f1 _rl_init_eightbit
0x7f0b4b3f10f2 rl_initialize
0x55ed3e503462 ???
0x55ed3e35a000 ???
0x55ed3e394a74 ???
0x55ed3e39586a ???
0x55ed3e149b4b ???
0x7f0b4a387209 ???
0x7f0b4a3872bb __libc_start_main
0x55ed3e14f399 ???
0xffffffffffffffff ???
---------------------
A fatal error internal to GDB has been detected, further
debugging is not possible.  GDB will now terminate.

This is a bug, please report it.  For instructions, see:
<https://www.gnu.org/software/gdb/bugs/>.

Segmentation fault (core dumped)

$ SHELL=/bin/sh gdb bash
(gdb) set env LC_ALL=ja_JP.UTF-8
(gdb) r
Starting program: /usr/bin/bash 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
bash: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7edeb59 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff7edeb59 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000055555563b682 in _rl_init_locale ()
#2  0x000055555563b772 in _rl_init_eightbit ()
#3  0x000055555561a66e in rl_initialize ()
#4  0x00005555555e5b05 in initialize_readline ()
#5  0x00005555555870a5 in ?? ()
#6  0x0000555555589aa1 in ?? ()
#7  0x000055555558beeb in ?? ()
#8  0x000055555559005b in yyparse ()
#9  0x0000555555586586 in parse_command ()
#10 0x0000555555586714 in read_command ()
#11 0x00005555555868c6 in reader_loop ()
#12 0x00005555555853b5 in main ()

```

**Comment by kanru** [comment]
This is probably a Debian libc6 bug because I can reproduce this in a VM. I'll report to them instead.
